PATH = "Water_Quality/dataset.csv"
URL = 'https://s3-ap-southeast-1.amazonaws.com/he-public-data/datasetab75fb3.zip'

DTYPES = {'Index':'int32',
          'pH':'float32',
          'Iron':'float32', 
          'Nitrate':'float32', 
          'Chloride':'float32', 
          'Lead':'float64', 
          'Zinc':'float32', 
          'Color':'object',
          'Turbidity':'float32', 
          'Fluoride':'float32', 
          'Copper':'float32', 
          'Odor':'float32', 
          'Sulfate':'float64', 
          'Conductivity':'float64', 
          'Chlorine':'float64',
          'Manganese':'float32', 
          'Total Dissolved Solids':'float64',  
          'Source':'object',
          'Water Temperature':'float64',
          'Air Temperature':'float64',
          'Month':'object',
          'Day':'float16',
          'Time of Day':'float16',
          'Target':'float16',
         }
MONTHS = {'January':1, 
          'February':2, 
          'March':3, 
          'April':4, 
          'May':5, 
          'June':6, 
          'July':7, 
          'August':8, 
          'September':9, 
          'October':10, 
          'November':11, 
          'December':12,
         }

# Water Quality Standards-------------------------------------------

# http://cgwb.gov.in/documents/wq-standards.pdf
INDIAN_STANDARDS = {'pH':[6.5, 8.5, 8.5],
                    'Iron':[0, 0.3, 0.3], 
                    'Nitrate':[0, 45, 45], 
                    'Chloride':[0, 250, 1000], 
                    'Lead':[0, 0.01, 0.05], 
                    'Zinc':[0, 5, 15], 
                    'Color':[0, 5, 15],
                    'Turbidity':[0, 1, 5], 
                    'Fluoride':[0, 1, 1.5], 
                    'Copper':[0, 0.05, 1.5], 
                    'Odor':[0, 1, 2], #max5
                    'Sulfate':[0, 200, 400], 
                    'Conductivity':[], 
                    'Chlorine':[0, 0.2, 1],
                    'Manganese':[0, 0.1, 0.3], 
                    'Total Dissolved Solids':[0, 500, 2000],  
                   }
# https://en.wikipedia.org/wiki/Drinking_water_quality_standards
EU_STANDARDS = {'pH':[],
                'Iron':[0, 0.2, 0.2], 
                'Nitrate':[0, 50, 50], 
                'Chloride':[0, 250, 250], 
                'Lead':[0, 0.01, 0.01], 
                'Zinc':[], 
                'Color':[],
                'Turbidity':[], 
                'Fluoride':[0, 1.5, 1.5], 
                'Copper':[0, 2, 2], 
                'Odor':[], #max5
                'Sulfate':[], 
                'Conductivity':[0, 2500, 2500], 
                'Chlorine':[0, 0.2, 1],
                'Manganese':[0, 0.05, 0.05], 
                'Total Dissolved Solids':[],  
               }